CREATE TABLE IF NOT EXISTS mpa (
id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(40) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS films (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(40) NOT NULL,
description TEXT,
release_date DATE,
duration INT,
mpa_id INT NOT NULL REFERENCES mpa(id)
);

CREATE TABLE IF NOT EXISTS users(
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
email VARCHAR(255) NOT NULL UNIQUE,
login VARCHAR(255) NOT NULL UNIQUE,
name VARCHAR(255),
birthday DATE
);

CREATE TABLE IF NOT EXISTS film_likes(
id_user BIGINT NOT NULL REFERENCES users(id),
id_film BIGINT NOT NULL REFERENCES films(id)
);

CREATE TABLE IF NOT EXISTS genres(
id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
name VARCHAR(40) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS film_genres(
film_id BIGINT NOT NULL REFERENCES films(id),
genre_id INT NOT NULL REFERENCES genres(id)
);

CREATE TABLE IF NOT EXISTS friendships(
id_user1 BIGINT NOT NULL REFERENCES users(id),
id_user2 BIGINT NOT NULL REFERENCES users(id),
PRIMARY KEY (id_user1, id_user2)
);